name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - name: Merge pull requests
      uses: pascalgn/automerge-action@v0.4.2
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        LABELS: "!wip,!work in progress,docs,documentation-updated"
        MERGE_METHOD: "squash"
        COMMIT_MESSAGE_TEMPLATE: "pull-request-title"
