name: GitHub Script with External
on: push
    
jobs:
  external:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get package.json
        id: data
        run: |
          echo "::set-output name=package::$(cat package.json | tr -d '\n')"
      - name: Test output
        run: |
          echo '${{ steps.data.outputs.package }}' | jq '.[]'
        env:
          JSON_DUMP: ${{ toJSON(steps.data.outputs.package) }}
      - uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/external.js`)
            script({ github, context, core, io }, ${{ steps.data.outputs.package }})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
