name: GitHub Script with External
on: push
    
jobs:
  external:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get package.json
        id: vars
        run: echo ::set-output name=vars::$(cat package.json)
      - name: Test output
        run: |
          echo '${{ steps.vars.outputs.package }}' | jq '.[]'
      - uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/external.js`)
            console.log(script({ github, context, core, io }, ${{ toJson(steps.vars.outputs.package) }}))
