name: GitHub Script with External
on: push
    
jobs:
  external:
    name: "Test on Node.js ${{ matrix.node }} OS: ${{matrix.os}}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [10]
    steps:
      - uses: actions/checkout@v2
      - name: get package.json
        id: data
        run: |
          echo "::set-output name=package::$(cat package.json | tr -d '\n')"
      - name: Install
        run: |
          npm install
      - name: Run eslint with eslint-plugin-vue-i18n
        run: |
          npm run lint:i18n -- -f json -o i18n-lint-raw-report.json
      - name: Filter eslint report
        run: |
          cat ./i18n-lint-raw-report.json | jq '[ .[] | select(.messages | length > 0) ] | .[] |= . + (.filePath | capture(".*packages\/(?<package>[a-zA-Z0-9_\\-]+)")) | group_by(.package)' > i18n-lint-report.json
      - name: Register i18n issues
        uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/external.js`)
            script({ github, context, core, io })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
