name: GitHub Script with External
on: push
    
jobs:
  external:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/external.js`)
            console.log(script({ github, context, core, io }))
