name: Node.js Matrix Build
on: [push]

jobs:
  build:
    name: Node.js ${{ matrix.os }} ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [8, 10]
        #node: [6, 8, 10]
    steps:
      - uses: actions/checkout@v1
      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: npm install
        run: |
          npm install
          npx vue -V
